#ifndef __CONFIG_H__
#define __CONFIG_H__

#define TEST_MODE 0
#define ENABLE_DEBUG 0

#define DEVICE_NAME "Test-1"
#define BLE_GATEWAY_NAME "cws-gateway"

#define CWS_DATA_CHAR_UUID "e202"
#define CWS_TIME_CHAR_UUID "e203"
#define CWS_BATTERY_CHAR_UUID "e204"
#define BLE_GATEWAY_ADDRESS "B8:27:EB:23:D8:12" // raspberry-pi

#define COMPASS_DECLINATION_ANGLE_DEGREE (+0.0)
#define COMPASS_DECLINATION_ANGLE_MINUTE (+19.0)

#define TEMP_POWER D3
#define IMU_I2C_ADDRESS 0x6A

#define DEVICE_NAME_LEN 16
#define BLE_SAMPLE_COUNT 9
#define BLE_MTU_SIZE (22 * BLE_SAMPLE_COUNT)

#if (1 == TEST_MODE)
#define TIMER0_INTERVAL_MS 100
#else
#define TIMER0_INTERVAL_MS 100
#endif

#define PCF8563_RTC 1
#define MCP7940_RTC 2
#define SELECTED_RTC MCP7940_RTC

#if (1 == TEST_MODE)
#define MAX_SAMPLE_COUNT 400
#define BLE_START_TRANMISSION_COUNT 50
#define BLE_RUN_TRANMISSION_UNTIL_COUNT 10
#else
#define MAX_SAMPLE_COUNT 2400
#define BLE_START_TRANMISSION_COUNT 1800
#define BLE_RUN_TRANMISSION_UNTIL_COUNT 20
#endif

#define MAX_MTU_SIZE 240
#define DEVICE_NAME_LEN 16
#define BLE_SAMPLE_COUNT 8
#define BLE_IMU_SMAPLE_SIZE 28
#define BLE_MTU_SIZE (BLE_IMU_SMAPLE_SIZE * BLE_SAMPLE_COUNT)

#define IMU_BUF_POS_COUNT 0
#define IMU_BUF_LEN_COUNT 4

#define IMU_BUF_POS_TIME 4
#define IMU_BUF_LEN_TIME 4

#define IMU_BUF_POS_ACC_X 8
#define IMU_BUF_POS_ACC_Y 10
#define IMU_BUF_POS_ACC_Z 12

#define IMU_BUF_LEN_ACC_X 2
#define IMU_BUF_LEN_ACC_Y 2
#define IMU_BUF_LEN_ACC_Z 2

#define IMU_BUF_POS_GYRO_X 14
#define IMU_BUF_POS_GYRO_Y 16
#define IMU_BUF_POS_GYRO_Z 18

#define IMU_BUF_LEN_GYRO_X 2
#define IMU_BUF_LEN_GYRO_Y 2
#define IMU_BUF_LEN_GYRO_Z 2

#define IMU_BUF_POS_MAG_X 20
#define IMU_BUF_POS_MAG_Y 22
#define IMU_BUF_POS_MAG_Z 24

#define IMU_BUF_LEN_MAG_X 2
#define IMU_BUF_LEN_MAG_Y 2
#define IMU_BUF_LEN_MAG_Z 2

#define IMU_BUF_POS_PEDO 26
#define IMU_BUF_LEN_PEDO 2

#endif // __CONFIG_H__
