#ifndef __CONFIG_H__
#define __CONFIG_H__

#define DEVICE_NAME "Cow-1"

#define TEST_MODE 0
#define ENABLE_DEBUG 0

#define TEMP_POWER D3
#define IMU_I2C_ADDRESS 0x6A

#define DEVICE_NAME_LEN 16
#define BLE_SAMPLE_COUNT 9
#define BLE_MTU_SIZE (22 * BLE_SAMPLE_COUNT)

#if (1 == TEST_MODE)
#define TIMER0_INTERVAL_MS 1000
#else
#define TIMER0_INTERVAL_MS 100
#endif

#define PCF8563_RTC 1
#define MCP7940_RTC 2
#define SELECTED_RTC PCF8563_RTC

#if (1 == TEST_MODE)
#define MAX_SAMPLE_COUNT 400
#define BLE_START_TRANMISSION_COUNT 50
#define BLE_RUN_TRANMISSION_UNTIL_COUNT 10
#else
#define MAX_SAMPLE_COUNT 2400
#define BLE_START_TRANMISSION_COUNT 1800
#define BLE_RUN_TRANMISSION_UNTIL_COUNT 20
#endif

#define MAX_MTU_SIZE 240
#define DEVICE_NAME_LEN 16
#define BLE_SAMPLE_COUNT 10
#define BLE_MTU_SIZE (22 * BLE_SAMPLE_COUNT)


#endif  // __CONFIG_H__
